name: Build Excel XLL

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build XLL
        run: cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FXLL2026-Binary
          path: build/Release/*.xll
